package org.springframework.samples.annotations;
// Generated 2008-5-8 3:35:49 by Hibernate Tools 3.2.0.b9


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Owners generated by hbm2java
 */
@Entity
@Table(name="OWNERS"
)
public class Owners  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String lastName;
     private String address;
     private String city;
     private String telephone;
     private Set<Pets> petses = new HashSet<Pets>(0);

    public Owners() {
    }

	
    public Owners(int id) {
        this.id = id;
    }
    public Owners(int id, String firstName, String lastName, String address, String city, String telephone, Set<Pets> petses) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.city = city;
       this.telephone = telephone;
       this.petses = petses;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="FIRST_NAME", length=30)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="LAST_NAME", length=30)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="ADDRESS")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="CITY", length=80)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="TELEPHONE", length=20)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="owners")
    public Set<Pets> getPetses() {
        return this.petses;
    }
    
    public void setPetses(Set<Pets> petses) {
        this.petses = petses;
    }




}


