package org.springframework.samples.annotations;
// Generated 2014-7-9 23:05:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Owners generated by hbm2java
 */
@Entity
@Table(name="OWNERS"
)
public class Owners  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String address;
     private String city;
     private String telephone;
     private Set<Pets> petses = new HashSet<Pets>(0);

    public Owners() {
    }

    public Owners(String firstName, String lastName, String address, String city, String telephone, Set<Pets> petses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.city = city;
       this.telephone = telephone;
       this.petses = petses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="FIRST_NAME", length=30)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", length=30)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="ADDRESS")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="CITY", length=80)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="TELEPHONE", length=20)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="owners")
    public Set<Pets> getPetses() {
        return this.petses;
    }
    
    public void setPetses(Set<Pets> petses) {
        this.petses = petses;
    }




}


