package org.springframework.samples.annotations;
// Generated 2014-7-9 23:01:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Types generated by hbm2java
 */
@Entity
@Table(name="TYPES"
)
public class Types  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Pets> petses = new HashSet<Pets>(0);

    public Types() {
    }

    public Types(String name, Set<Pets> petses) {
       this.name = name;
       this.petses = petses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="NAME", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="types")
    public Set<Pets> getPetses() {
        return this.petses;
    }
    
    public void setPetses(Set<Pets> petses) {
        this.petses = petses;
    }




}


