package org.springframework.samples.annotations;
// Generated 2008-5-8 3:35:49 by Hibernate Tools 3.2.0.b9


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Types generated by hbm2java
 */
@Entity
@Table(name="TYPES"
)
public class Types  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Pets> petses = new HashSet<Pets>(0);

    public Types() {
    }

	
    public Types(int id) {
        this.id = id;
    }
    public Types(int id, String name, Set<Pets> petses) {
       this.id = id;
       this.name = name;
       this.petses = petses;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="NAME", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="types")
    public Set<Pets> getPetses() {
        return this.petses;
    }
    
    public void setPetses(Set<Pets> petses) {
        this.petses = petses;
    }




}


