package org.springframework.samples.annotations;
// Generated 2014-7-9 23:05:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vets generated by hbm2java
 */
@Entity
@Table(name="VETS"
)
public class Vets  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private Set<VetSpecialties> vetSpecialtieses = new HashSet<VetSpecialties>(0);

    public Vets() {
    }

    public Vets(String firstName, String lastName, Set<VetSpecialties> vetSpecialtieses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.vetSpecialtieses = vetSpecialtieses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="FIRST_NAME", length=30)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", length=30)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vets")
    public Set<VetSpecialties> getVetSpecialtieses() {
        return this.vetSpecialtieses;
    }
    
    public void setVetSpecialtieses(Set<VetSpecialties> vetSpecialtieses) {
        this.vetSpecialtieses = vetSpecialtieses;
    }




}


