package test.entityjpa;
// Generated 2008-5-10 12:53:16 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Specialties generated by hbm2java
 */
@Entity
@Table(name="SPECIALTIES"
)
public class Specialties  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Vets> vetses = new HashSet<Vets>(0);

    public Specialties() {
    }

	
    public Specialties(int id) {
        this.id = id;
    }
    public Specialties(int id, String name, Set<Vets> vetses) {
       this.id = id;
       this.name = name;
       this.vetses = vetses;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="NAME", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="VET_SPECIALTIES", joinColumns = { 
        @JoinColumn(name="SPECIALTY_ID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="VET_ID", nullable=false, updatable=false) })
    public Set<Vets> getVetses() {
        return this.vetses;
    }
    
    public void setVetses(Set<Vets> vetses) {
        this.vetses = vetses;
    }




}


