package test.entityjpa;
// Generated 2008-5-10 12:53:16 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Vets generated by hbm2java
 */
@Entity
@Table(name="VETS"
)
public class Vets  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String lastName;
     private Set<Specialties> specialtieses = new HashSet<Specialties>(0);

    public Vets() {
    }

	
    public Vets(int id) {
        this.id = id;
    }
    public Vets(int id, String firstName, String lastName, Set<Specialties> specialtieses) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.specialtieses = specialtieses;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="FIRST_NAME", length=30)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="LAST_NAME", length=30)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="VET_SPECIALTIES", joinColumns = { 
        @JoinColumn(name="VET_ID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="SPECIALTY_ID", nullable=false, updatable=false) })
    public Set<Specialties> getSpecialtieses() {
        return this.specialtieses;
    }
    
    public void setSpecialtieses(Set<Specialties> specialtieses) {
        this.specialtieses = specialtieses;
    }




}


