/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2014-06-30 07:54:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Enumeration;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      test.SessionProcess sessionProcess = null;
      synchronized (session) {
        sessionProcess = (test.SessionProcess) _jspx_page_context.getAttribute("sessionProcess", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (sessionProcess == null){
          sessionProcess = new test.SessionProcess();
          _jspx_page_context.setAttribute("sessionProcess", sessionProcess, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=gbk\" />\r\n");
      out.write("<head>\r\n");
      out.write("<title>演练request、session作用范围的使用</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<fieldset style=\"background:#fedcba\"><legend>新增会话属性</legend>\r\n");
      out.write("<form method=\"post\" name=\"form1\" action=\"index.jsp\">\r\n");
      out.write("<table border=\"0\" cellspacing=\"1\" cellpadding=\"1\" width=\"200\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td nowrap><b>请添加session属性名：</b></td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"name\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><b>session属性值：</b></td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"value\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" align=center>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"新增\" name=\"add\" />\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</center>\r\n");
      out.write("</form>\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<fieldset style=\"background:#fedcba\"><legend>打印会话属性</legend>\r\n");
      out.write("<center>\r\n");
      out.write("<table border=\"0\" cellspacing=\"10\"\r\n");
      out.write("\tcellpadding=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td valign=\"top\">\r\n");
      out.write("\t\t");

				if (request.getParameter("add") != null) {					
					String nameItem = request.getParameter("name");					
					if (nameItem != null && nameItem.trim().length() > 0)
						session.setAttribute(nameItem, request.getParameter("value"));
				}
		
      out.write("\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<table border=1 cellspacing=\"1\" cellpadding=5 width=300 bgcolor=#dddddd>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center><b>键</b></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center><b>值</b></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					Enumeration sessionNams = session.getAttributeNames();
					while (sessionNams.hasMoreElements()) {
						String name = (String) sessionNams.nextElement();
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( name );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( "" + session.getAttribute(name) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

				}
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<form method=\"post\" name=\"form2\" action=\"destroy.jsp\">\r\n");
      out.write("<table border=\"0\" cellspacing=\"1\" cellpadding=\"1\" width=\"200\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=center>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"失效当前session\" name=\"destroy\" />\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</center>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</center>\r\n");
      out.write("</fieldset>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");

	sessionProcess.processSessionContent(session);

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
