package org.springframework.samples;
// Generated 2008-5-8 14:10:19 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pets generated by hbm2java
 */
public class Pets  implements java.io.Serializable {


     private int id;
     private Types types;
     private Owners owners;
     private String name;
     private Date birthDate;
     private Set visitses = new HashSet(0);

    public Pets() {
    }

	
    public Pets(int id, Types types, Owners owners) {
        this.id = id;
        this.types = types;
        this.owners = owners;
    }
    public Pets(int id, Types types, Owners owners, String name, Date birthDate, Set visitses) {
       this.id = id;
       this.types = types;
       this.owners = owners;
       this.name = name;
       this.birthDate = birthDate;
       this.visitses = visitses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Types getTypes() {
        return this.types;
    }
    
    public void setTypes(Types types) {
        this.types = types;
    }
    public Owners getOwners() {
        return this.owners;
    }
    
    public void setOwners(Owners owners) {
        this.owners = owners;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public Set getVisitses() {
        return this.visitses;
    }
    
    public void setVisitses(Set visitses) {
        this.visitses = visitses;
    }




}


