package org.springframework.samples;
// Generated 2014-7-9 0:10:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pets generated by hbm2java
 */
public class Pets  implements java.io.Serializable {


     private Integer id;
     private Owners owners;
     private Types types;
     private String name;
     private Date birthDate;
     private Set visitses = new HashSet(0);

    public Pets() {
    }

	
    public Pets(Owners owners, Types types) {
        this.owners = owners;
        this.types = types;
    }
    public Pets(Owners owners, Types types, String name, Date birthDate, Set visitses) {
       this.owners = owners;
       this.types = types;
       this.name = name;
       this.birthDate = birthDate;
       this.visitses = visitses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Owners getOwners() {
        return this.owners;
    }
    
    public void setOwners(Owners owners) {
        this.owners = owners;
    }
    public Types getTypes() {
        return this.types;
    }
    
    public void setTypes(Types types) {
        this.types = types;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public Set getVisitses() {
        return this.visitses;
    }
    
    public void setVisitses(Set visitses) {
        this.visitses = visitses;
    }




}


