package org.springframework.samples;
// Generated 2008-5-8 14:10:19 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Specialties generated by hbm2java
 */
public class Specialties  implements java.io.Serializable {


     private int id;
     private String name;
     private Set vetses = new HashSet(0);

    public Specialties() {
    }

	
    public Specialties(int id) {
        this.id = id;
    }
    public Specialties(int id, String name, Set vetses) {
       this.id = id;
       this.name = name;
       this.vetses = vetses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getVetses() {
        return this.vetses;
    }
    
    public void setVetses(Set vetses) {
        this.vetses = vetses;
    }




}


