package org.springframework.samples;
// Generated 2014-7-9 0:10:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Specialties generated by hbm2java
 */
public class Specialties  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set vetSpecialtieses = new HashSet(0);

    public Specialties() {
    }

    public Specialties(String name, Set vetSpecialtieses) {
       this.name = name;
       this.vetSpecialtieses = vetSpecialtieses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getVetSpecialtieses() {
        return this.vetSpecialtieses;
    }
    
    public void setVetSpecialtieses(Set vetSpecialtieses) {
        this.vetSpecialtieses = vetSpecialtieses;
    }




}


