package org.springframework.samples;
// Generated 2008-5-8 14:10:19 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Types generated by hbm2java
 */
public class Types  implements java.io.Serializable {


     private int id;
     private String name;
     private Set petses = new HashSet(0);

    public Types() {
    }

	
    public Types(int id) {
        this.id = id;
    }
    public Types(int id, String name, Set petses) {
       this.id = id;
       this.name = name;
       this.petses = petses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPetses() {
        return this.petses;
    }
    
    public void setPetses(Set petses) {
        this.petses = petses;
    }




}


