package org.springframework.samples;
// Generated 2014-7-9 0:10:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Types generated by hbm2java
 */
public class Types  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set petses = new HashSet(0);

    public Types() {
    }

    public Types(String name, Set petses) {
       this.name = name;
       this.petses = petses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPetses() {
        return this.petses;
    }
    
    public void setPetses(Set petses) {
        this.petses = petses;
    }




}


