package org.springframework.samples;
// Generated 2008-5-8 14:10:19 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Vets generated by hbm2java
 */
public class Vets  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String lastName;
     private Set specialtieses = new HashSet(0);

    public Vets() {
    }

	
    public Vets(int id) {
        this.id = id;
    }
    public Vets(int id, String firstName, String lastName, Set specialtieses) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.specialtieses = specialtieses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Set getSpecialtieses() {
        return this.specialtieses;
    }
    
    public void setSpecialtieses(Set specialtieses) {
        this.specialtieses = specialtieses;
    }




}


