package org.springframework.samples;
// Generated 2014-7-9 0:10:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vets generated by hbm2java
 */
public class Vets  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private Set vetSpecialtieses = new HashSet(0);

    public Vets() {
    }

    public Vets(String firstName, String lastName, Set vetSpecialtieses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.vetSpecialtieses = vetSpecialtieses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Set getVetSpecialtieses() {
        return this.vetSpecialtieses;
    }
    
    public void setVetSpecialtieses(Set vetSpecialtieses) {
        this.vetSpecialtieses = vetSpecialtieses;
    }




}


