package org.springframework.samples;
// Generated 2014-7-9 0:10:44 by Hibernate Tools 4.3.1



/**
 * VetSpecialties generated by hbm2java
 */
public class VetSpecialties  implements java.io.Serializable {


     private VetSpecialtiesId id;
     private Specialties specialties;
     private Vets vets;

    public VetSpecialties() {
    }

    public VetSpecialties(VetSpecialtiesId id, Specialties specialties, Vets vets) {
       this.id = id;
       this.specialties = specialties;
       this.vets = vets;
    }
   
    public VetSpecialtiesId getId() {
        return this.id;
    }
    
    public void setId(VetSpecialtiesId id) {
        this.id = id;
    }
    public Specialties getSpecialties() {
        return this.specialties;
    }
    
    public void setSpecialties(Specialties specialties) {
        this.specialties = specialties;
    }
    public Vets getVets() {
        return this.vets;
    }
    
    public void setVets(Vets vets) {
        this.vets = vets;
    }




}


